upstream questionproject {
    server 127.0.0.1:8000;
    server 127.0.0.1:8001 max_fails=3 fail_timeout=30s;
    server 127.0.0.1:8002 weight=10;
    server 127.0.0.1:8003 backup;
}

# proxy_cache_path /Users/a.mahonin/questionproject/sem61/nginx_cache levels=1:2 keys_zone=questionproject_zone:10m inactive=24h max_size=50m;

server {
    listen 80 default_server;
    server_name questionproject.localhost;

    access_log /var/log/nginx/questionproject_access.log;
    error_log /var/log/nginx/questionproject_error.log;

    # location /static {
    #     # Дополнение пути
    #     root /Users/a.mahonin/questionproject/;
    # }
    location /static/ {
        # Может не быть прав - нужно выдавать на чтение
        alias /Users/a.mahonin/questionproject/collected_static/;
        access_log off;
    }

    # location /media {
    #     # Дополнение пути
    #     root /Users/a.mahonin/questionproject/;
    #     access_log off;
    # }
    location /media/ {
        # Дополнение пути
        alias /Users/a.mahonin/questionproject/media/;
    }

    location / {
        proxy_pass http://questionproject;
        proxy_set_header Host $host;
        # proxy_cache questionproject_zone;
        # proxy_cache_valid 200 302 10m;
    }
}