# Generated by Django 5.2.7 on 2025-12-04 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sem51', '0002_userimagelike'),
    ]

    operations = [
        migrations.AddField(
            model_name='userimagelike',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
