# Generated by Django 5.2.7 on 2025-12-04 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sem51', '0003_userimagelike_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='userimage',
            name='likes_cnt',
            field=models.IntegerField(default=0, help_text='[Денормализация]'),
        ),
    ]
