# Generated by Django 5.2.7 on 2025-11-06 15:57

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gramm', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='commentlikes',
            unique_together={('user', 'comment')},
        ),
        migrations.AlterUniqueTogether(
            name='postlikes',
            unique_together={('user', 'post')},
        ),
    ]
