# Generated by Django 5.2.7 on 2025-11-06 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gramm', '0002_alter_comment_options_alter_commentlikes_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'Комментарий', 'verbose_name_plural': 'Комментарии'},
        ),
        migrations.AlterModelOptions(
            name='commentlikes',
            options={'verbose_name': 'Лайк к коментарию', 'verbose_name_plural': 'Лайки к коментариям'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'Пост', 'verbose_name_plural': 'Посты'},
        ),
        migrations.AlterModelOptions(
            name='postlikes',
            options={'verbose_name': 'Лайк к посту', 'verbose_name_plural': 'Лайки к постам'},
        ),
        migrations.AddField(
            model_name='post',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Если TRUE - отображается пользователям', verbose_name='Активно?'),
        ),
    ]
