# Generated by Django 5.2.7 on 2025-11-06 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gramm', '0003_alter_comment_options_alter_commentlikes_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('published', 'Опубликован'), ('archived', 'Архивирован'), ('draft', 'Черновик')], default='draft', verbose_name='Статус опубликованности'),
        ),
    ]
