# Generated by Django 5.2.7 on 2025-11-06 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gramm', '0005_alter_comment_parent_comment_alter_comment_post_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Время создания поста'),
        ),
    ]
