# Generated by Django 5.2.7 on 2025-12-04 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sem5', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='likes_cnt',
            field=models.IntegerField(default=0, help_text='[Денормализация]'),
        ),
    ]
